version: '3.8'

services:
  mariadb:
    container_name: mariadb-lugeasy-local
    image: mariadb:latest
    ports:
      - ${MARIADB_OUTER_PORT}:${MARIADB_INNER_PORT}
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      lugeasy_network:
        ipv4_address: ${NETWORK_MARIADB_IP}
  redis:
    container_name: redis-lugeasy-local
    image: redis:latest
    ports:
      - ${REDIS_OUTER_PORT}:${REDIS_INNER_PORT}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      lugeasy_network:
        ipv4_address: ${NETWORK_REDIS_IP}
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus-lugeasy-container
#    volumes:
#      - ./config/prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    networks:
#      lugeasy_network:
#        ipv4_address: ${NETWORK_PROMETHEUS_IP}
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana-lugeasy-local
#    ports:
#      - "3000:3000"
#    networks:
#      lugeasy_network:
#        ipv4_address: ${NETWORK_GRAFANA_IP}

networks:
  lugeasy_network:
    name: lugeasy_network-local
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          ip_range: ${NETWORK_IP_RANGE}
          gateway: ${NETWORK_GATEWAY}